---
title: "Untitled"
author: "Ying Fang Lee"
date: "2024-12-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(DBI)      #Database infrastructure for R
library(RMySQL)   #Translating R and MySQL
library(tidyverse)#Organize data

#create a config.yml file with database information in it
#default:
#  datawarehouse:
#    driver: 'MySQL()' 
#    server: 'Name_or_link_for_Database'
#    uid: 'Database_Username'
#    pwd: 'Database_Password'
#    database: 'Name_of_Database'

#Use get() from config library to get database information from config.yml
dbConfig <- config::get("datawarehouse")

#Connecting to Database with config info
mydb <- dbConnect(
  MySQL(),
  user = dbConfig$uid,
  password = dbConfig$pwd,
  dbname = dbConfig$database,
  host = dbConfig$server
)
```

```{r}
#To see the tables in the database
dbListTables(mydb)

#Convert the information from MySQL to R data frame
MovieInfo <- tbl(mydb, "movieinfo") #convert source data to table
MovieInfo_df <- collect(MovieInfo) #convert table to R data frame
head(MovieInfo_df)
dbDisconnect(mydb) #Disconnect from database
```

