---
title: "Project_2"
author: "Ying Fang Lee"
date: "10/13/2024"
output: html_document
---
My data
```{r}
library(tidyverse)
url <-"https://raw.githubusercontent.com/amily52131/DATA607/refs/heads/main/Project_2/candyhierarchy2017.csv"
file<- read.csv(url)
# Taking care of empty spaces and set them to NA
file[file ==""] <- NA
# Changing the ranking for candy to number for analysis later
file[file=="MEH"] <- 1
file[file=="JOY"] <- 2
file[file=="DESPAIR"] <- 3
```

Cleaning Up States
```{r}
US_States <- file$Q5..STATE..PROVINCE..COUNTY..ETC

# State Patterns

sname <- c("Washington DC|DISTRICT OF COLUMBIA" ,  "Alabama"  , "Alaska"  , "American Samoa" ,   "Arizona" ,  "Arkansas" ,  "California" , "Colorado" , "Connecticut" , "Delaware" , "Florida" , "Georgia" , "Guam" , "Hawaii"  ,  "Idaho"  ,  "Illinois"  ,  "Indiana"  ,  "Iowa" , "Kansas" , "Kentucky" , "Louisiana" , "Maine" , "Maryland" , "Massachusetts" , "Michigan" , "Minnesota" , "Mississippi" , "Missouri" , "Montana" , "Nebraska" , "Nevada" , "New Hampshire" , "New Jersey" , "New Mexico" , "New York" , "North Carolina" , "North Dakota" , "Ohio" , "Oklahoma" , "Oregon" , "Pennsylvania" , "Puerto Rico" , "Rhode Island" , "South Carolina" , "South Dakota" , "Tennessee" , "Texas" , "Utah" , "Vermont" , "Virginia" , "Washington" , "West Virginia" , "Wisconsin" , "Wyoming")
states2 <- c("DC" , "AL" , "AK" , "AS" , "AZ" , "AR" , "CA" , "CO" , "CT" , "DE" , "FL" , "GA" , "GU" , "HI" , "ID" , "IL" , "IN" , "IA" , "KS" , "KY" , "LA" , "ME" , "MD" , "MA" , "MI" , "MN" , "MS" , "MO" , "MT" , "NE" , "NV" , "NH" , "NJ" , "NM" , "NY" , "NC" , "ND" , "OH" , "OK" , "OR" , "PA" , "PR" , "RI" , "SC" , "SD" , "TN" , "TX" , "UT" , "VT" , "VA" , "WA" , "WV" , "WI" , "WY")

spattern <- data.frame(sname ,  states2)

# first iteration of states to convert state name to two letter abbreviation
for(s in spattern$sname){
  States <- grep(s ,  US_States , ignore.case = TRUE)
  #print(spattern$temp[spattern$pstates==s])
  US_States[States] <- toupper(spattern$states2[spattern$sname==s])
}

# helper function to check if state pattern exists in the string
return_logic <- function(spattern, string){
  b <- FALSE
  w <- strsplit(string, " ")
  for (c in w){
    if(2 %in%str_length(c) && TRUE %in% grepl(spattern, c, ignore.case = TRUE)){
      b <- TRUE
    }
  }
  returnValue(b)
}
# second iteration of states to convert state name to two letter abbreviation
for (s in spattern$states2) {
  for (x in US_States) {
    if (return_logic(s,x) == TRUE){
      US_States[US_States==x] <- s
    }
  }
}
file$Q5..STATE..PROVINCE..COUNTY..ETC <- as.data.frame(US_States)
```

Cleaning Up Country

```{r}
# Clean up country names 
Countries <- file$Q4..COUNTRY %>% toupper() %>% str_trim()

# Pattern to match
pat <- c("USA","U.S.A", "U.S","United States","Costa Rica")
# Other countries
opat <- c("England", "Canada", "Mexico","Germany")


for (p in pat){
  matches <- agrep(p, Countries,ignore.case = TRUE, max.distance = 1)
  Countries[matches] <- "USA"
}
for (p in opat){
  matches <- agrep(p, Countries,ignore.case = TRUE, max.distance = 1)
  Countries[matches] <- toupper(p)
}
for(s in spattern$sname){
  matches <- grep(s ,  Countries , ignore.case = TRUE)
  Countries[matches] <- "USA"
}

file$Q4..COUNTRY <- as.data.frame(Countries)


```


```{r}

```

